CREATE DATABASE devchu_images;
USE devchu_images;

CREATE TABLE users (
    id CHAR(36) PRIMARY KEY NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name VARCHAR(50) NOT NULL,
    avatar VARCHAR(255),
    accountStatus ENUM ('VERIFIED', 'UNVERIFIED', 'BANNED') DEFAULT 'UNVERIFIED',
    role ENUM ('ROLE_CUSTOMER', 'ROLE_ADMIN', 'ROLE_EDITOR') DEFAULT 'ROLE_CUSTOMER',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE uploaded_files (
    id CHAR(36) PRIMARY KEY NOT NULL,
    title VARCHAR(100) UNIQUE NOT NULL,
    price DOUBLE DEFAULT 0,
    `root` VARCHAR(255),
    display VARCHAR(255),
    medium VARCHAR(255),
    high VARCHAR(255),
    `size` DECIMAL(4, 2),
    width SMALLINT UNSIGNED,
    height SMALLINT UNSIGNED,
    `status` ENUM ("ACTIVE", "INACTIVE", "DELETED") DEFAULT "ACTIVE",
    file_type ENUM ("jpeg", "jpg", "png"),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId CHAR(36) NOT NULL,
    CONSTRAINT fk_file_user FOREIGN KEY (userId) REFERENCES users (id)
);

ALTER TABLE uploaded_files
ADD FULLTEXT INDEX ft_title (title);

CREATE TABLE comments (
    id CHAR(36) PRIMARY KEY NOT NULL,
    content TEXT NOT NULL,
    `status` ENUM ("ACTIVE", "INACTIVE", "DELETED") DEFAULT "ACTIVE",
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId CHAR(36) NOT NULL,
    fileId CHAR(36) NOT NULL,
    CONSTRAINT fk_comment_user FOREIGN KEY (userId) REFERENCES users (id),
    CONSTRAINT fk_comment_file FOREIGN KEY (fileId) REFERENCES files (id)
);

CREATE TABLE receipts (
    id CHAR(36) PRIMARY KEY NOT NULL,
    totalPrice DOUBLE NOT NULL,
    method ENUM ("MOMO", "CASH") DEFAULT "CASH",
    methodId VARCHAR(100),
    `status` ENUM ("ACTIVE", "INACTIVE", "DELETED") DEFAULT "ACTIVE",
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId CHAR(36) NOT NULL,
    CONSTRAINT fk_receipt_user FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE receipt_details (
    id CHAR(36) PRIMARY KEY NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    receiptId CHAR(36) NOT NULL,
    fileId CHAR(36) NOT NULL,
    CONSTRAINT fk_receipt_detail_receipt FOREIGN KEY (receiptId) REFERENCES receipts (id),
    CONSTRAINT fk_receipt_detail_file FOREIGN KEY (fileId) REFERENCES files (id)
);

CREATE TABLE refresh_tokens (
    id CHAR(36) PRIMARY KEY NOT NULL,
    token VARCHAR(100) NOT NULL,
    expire_date DATE NOT NULL,
    `status` ENUM ("ACTIVE", "INACTIVE", "DELETED") DEFAULT "ACTIVE",
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userId CHAR(36) NOT NULL,
    CONSTRAINT fk_token_user FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE tags (
    id CHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    `status` ENUM ("ACTIVE", "INACTIVE", "DELETED") DEFAULT "ACTIVE",
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE file_tags (
    id CHAR(36) PRIMARY KEY NOT NULL,
    fileId CHAR(36) NOT NULL,
    tagId CHAR(36) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_file_tag FOREIGN KEY (fileId) REFERENCES files (id),
    CONSTRAINT fk_tag_file FOREIGN KEY (tagId) REFERENCES tags (id)
);

CREATE TABLE user_rights (
    id CHAR(36) PRIMARY KEY NOT NULL,
    expire_date DATE NOT NULL,
    fileId CHAR(36) NOT NULL,
    userId CHAR(36) NOT NULL,
    `status` ENUM ("ACTIVE", "INACTIVE", "DELETED") DEFAULT "ACTIVE",
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_right_file FOREIGN KEY (fileId) REFERENCES files (id),
    CONSTRAINT fk_right_user FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE verification_codes (
    id CHAR(36) PRIMARY KEY NOT NULL,
    value CHAR(36) NOT NULL,
    userId CHAR(36) NOT NULL,
    `status` ENUM ("ACTIVE", "INACTIVE", "DELETED") DEFAULT "ACTIVE",
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_code_user FOREIGN KEY (userId) REFERENCES users (id)
);

